### ISSUE TITLE
Rename `Domains` to `Services`

### ISSUE THREAD

**Issue by palanglung** [HalalData/backend#14]
Because for my point of view the function of what we call now Domains is to give service to controller that maybe not relate only for one model. 

Thanks

**Comment by karuna** [comment]
:+1:

**Comment by bepitulaz** [comment]
Laksanakeun!

**Comment by bepitulaz** [comment]
check [#15](https://github.com/HalalData/backend/pull/15)

**Comment by bepitulaz** [comment]
I can close this issue now.
